# Kubernetes Deployment template for ECR images
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain-shipper-portal
  namespace: default
  labels:
    app.kubernetes.io/name: rain-shipper-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rain-shipper-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rain-shipper-portal
    spec:
      containers:
      - name: rain-shipper-portal
        image: 748809150323.dkr.ecr.us-west-2.amazonaws.com/rain-shipper-portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
          privileged: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi

---
# Kubernetes Service template for LoadBalancer services
apiVersion: v1
kind: Service
metadata:
  name: rain-shipper-portal
  namespace: default
  labels:
    app.kubernetes.io/name: rain-shipper-portal
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: rain-shipper-portal
